{% set version = "1.2" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: html5rdf
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/html5rdf/html5rdf-{{ version }}.tar.gz
  sha256: 08378cbbbb63993ba7bb5eb1eac44bf9ca7b1a23dbee3d2afef5376597fb00a5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8

test:
  imports:
    - html5rdf
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: html5rdf

  - name: html5rdf-with-chardet
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("html5rdf", max_pin="x.x.x") }}
        - chardet >=2.2.1
    test:
      imports:
        - html5rdf
      commands:
        - pip check
      requires:
        - pip

  - name: html5rdf-with-lxml
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("html5rdf", max_pin="x.x.x") }}
        - lxml >=3.4.0
    test:
      imports:
        - html5rdf
      commands:
        - pip check
      requires:
        - pip

  - name: html5rdf-with-genshi
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("html5rdf", max_pin="x.x.x") }}
        - genshi >=0.7.1
    test:
      imports:
        - html5rdf
      commands:
        - pip check
      requires:
        - pip

  - name: html5rdf-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("html5rdf-with-chardet", max_pin="x.x.x") }}
        - {{ pin_subpackage("html5rdf-with-genshi", max_pin="x.x.x") }}
        - {{ pin_subpackage("html5rdf-with-lxml", max_pin="x.x.x") }}
        - {{ pin_subpackage("html5rdf", max_pin="x.x.x") }}
    test:
      imports:
        - html5rdf
      commands:
        - pip check
        # TODO: run test suite after one of 
        # - https://github.com/RDFLib/html5rdf/issues/1
        # - https://github.com/RDFLib/html5rdf/pull/2
      requires:
        - pip

about:
  home: https://github.com/RDFLib/html5rdf
  summary: HTML parser based on the WHATWG HTML specification
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
