{% set version = "1.2.1" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: html5rdf
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/html5rdf/html5rdf-{{ version }}.tar.gz
  sha256: ace9b420ce52995bb4f05e7425eedf19e433c981dfe7a831ab391e2fa2e1a195

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - html5rdf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

outputs:
  - name: html5rdf

  - name: html5rdf-with-chardet
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("html5rdf", max_pin="x.x.x") }}
        - chardet >=2.2.1
    test:
      imports:
        - html5rdf
      commands:
        - pip check
      requires:
        - pip

  - name: html5rdf-with-lxml
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("html5rdf", max_pin="x.x.x") }}
        - lxml >=3.4.0
    test:
      imports:
        - html5rdf
      commands:
        - pip check
      requires:
        - pip

  - name: html5rdf-with-genshi
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("html5rdf", max_pin="x.x.x") }}
        - genshi >=0.7.1
    test:
      imports:
        - html5rdf
      commands:
        - pip check
      requires:
        - pip

  - name: html5rdf-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("html5rdf-with-chardet", max_pin="x.x.x") }}
        - {{ pin_subpackage("html5rdf-with-genshi", max_pin="x.x.x") }}
        - {{ pin_subpackage("html5rdf-with-lxml", max_pin="x.x.x") }}
        - {{ pin_subpackage("html5rdf", max_pin="x.x.x") }}
    test:
      imports:
        - html5rdf
      commands:
        - pip check
        # TODO: run test suite after one of 
        # - https://github.com/RDFLib/html5rdf/issues/1
        # - https://github.com/RDFLib/html5rdf/pull/2
      requires:
        - pip

about:
  home: https://github.com/RDFLib/html5rdf
  summary: HTML parser based on the WHATWG HTML specification
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
